# Guard against spurious index-versus-yield regression ------------------------

#' Guard against the spurious index-versus-yield regression
#'
#' A common claim regresses a dependence index against absolute yield across
#' units (e.g. varieties). When the index is the Relative Interaction Index,
#' `(open - cage) / (open + cage)`, and the yield axis is the open-arm value,
#' the open term appears on both axes, so a positive slope is partly guaranteed
#' by construction (Pearson's 1897 spurious correlation of indices sharing a
#' term). This guard quantifies how much of the observed slope is mechanical.
#'
#' The null is generated by permuting the exclusion-arm values across units
#' while holding the open-arm values fixed: this destroys any genuine open-cage
#' relationship but retains the shared-open coupling, so the permutation
#' distribution of the slope is the slope expected from coupling alone. A
#' permutation p-value near 1 means the observed slope is consistent with pure
#' coupling -- i.e. spurious. Optionally supply a decoupled yield axis (e.g. the
#' exclusion-arm yield, or an independent vigour covariate) on which the index
#' may be regressed without sharing a term.
#'
#' @param open Numeric vector of open-arm values, one per unit.
#' @param cage Numeric vector of exclusion-arm values, one per unit.
#' @param n_perm Number of permutations.
#' @param decouple Optional numeric vector (one per unit) giving a yield axis
#'   that does not share a term with the index.
#' @param seed Optional integer seed.
#'
#' @return An object of class `pollin_spurious`.
#' @export
#' @examples
#' set.seed(1)
#' # independent arms: any index~open slope here is purely mechanical
#' g <- pollin_guard_spurious(rpois(10, 30), rpois(10, 25),
#'                            n_perm = 200, seed = 1)
#' g
pollin_guard_spurious <- function(
  open,
  cage,
  n_perm = 999L,
  decouple = NULL,
  seed = NULL
) {
  if (length(open) != length(cage)) {
    stop(
      "`open` and `cage` must be the same length (one per unit).",
      call. = FALSE
    )
  }
  ok <- is.finite(open) & is.finite(cage) & (open + cage) > 0
  open <- open[ok]
  cage <- cage[ok]
  rii <- (open - cage) / (open + cage)
  obs <- unname(stats::coef(stats::lm(rii ~ open))[2L])
  if (!is.null(seed)) {
    set.seed(seed)
  }
  perm <- vapply(
    seq_len(n_perm),
    function(i) {
      cg <- sample(cage)
      r <- (open - cg) / (open + cg)
      keep <- is.finite(r)
      unname(stats::coef(stats::lm(r[keep] ~ open[keep]))[2L])
    },
    numeric(1)
  )
  p_perm <- (sum(abs(perm) >= abs(obs), na.rm = TRUE) + 1) / (n_perm + 1)
  out <- list(
    observed_slope = obs,
    perm_p = p_perm,
    perm_mean = mean(perm, na.rm = TRUE),
    perm_sd = stats::sd(perm, na.rm = TRUE),
    n = length(open),
    n_perm = n_perm,
    decoupled = NULL
  )
  if (!is.null(decouple)) {
    dc <- decouple[ok]
    fit <- stats::lm(rii ~ dc)
    sm <- summary(fit)$coefficients
    out$decoupled <- list(slope = unname(coef(fit)[2L]), p.value = sm[2L, 4L])
  }
  structure(out, class = "pollin_spurious")
}

#' @export
print.pollin_spurious <- function(x, ...) {
  cat("<pollin_spurious>  index ~ open-yield slope guard\n")
  cat(sprintf("  observed slope : %.4f\n", x$observed_slope))
  cat(sprintf(
    "  coupling null  : mean %.4f, sd %.4f (n_perm = %d)\n",
    x$perm_mean,
    x$perm_sd,
    x$n_perm
  ))
  cat(sprintf(
    "  permutation p  : %.3f  -> %s\n",
    x$perm_p,
    if (x$perm_p > 0.1) {
      "slope consistent with mechanical coupling (SPURIOUS risk)"
    } else {
      "slope exceeds coupling null (some genuine signal)"
    }
  ))
  if (!is.null(x$decoupled)) {
    cat(sprintf(
      "  decoupled axis : slope %.4f, p = %.3f (no shared term)\n",
      x$decoupled$slope,
      x$decoupled$p.value
    ))
  }
  invisible(x)
}
